    private void foo() throws java.sql.SQLException {
    }

