    public void foo() throws NamingException {
    }

