    void methdo2() throws java.awt.AWTException
    {
    }

