    @Test
    public void testUsageHelpPrint()
            throws Exception {
        exit.checkAssertionAfterwards(() -> {
            assertEquals("Unexpected output log",
                    USAGE,
                    systemOut.getLog());
            assertEquals("Unexpected system error log", "", systemErr.getLog());
        });
        Main.main("-h");
    }

