    public void foo36() throws Exception {
        throw new Exception("",
            new Exception()
        );
// violation
    }

