    /** Do 2.
     * @throws TestException2 when error occurs.
     */
    private static void doStuff2() throws TestException2 {
        throw new TestException2("");
    }

