    // This should pass for our reconfigured throwsIndent test.
    private void myFunc()
            throws Exception
    {
    }

